apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/frontend
images:
- name: ghcr.io/abdelkarim-ensi/aiops-frontend
  newName: ghcr.io/abdelkarim-ensi/aiops-frontend
  newTag: a135c48bf02470136b37542413235fa89b0306f4
